name: Unity Test Runner Example

on:
  push:
    branches:
    - master

jobs:
  editorTestJob:
    strategy:
      matrix:
        unity-tag: [2018.4.9f1]
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    steps:
      - uses: actions/checkout@master
      - name: Run Tests
        env:
          CYPHER_KEY: ${{ secrets.cypherkey }}
        run: |
          openssl aes-256-cbc -d -in Unity_v2018.x.ulf-cipher -k ${CYPHER_KEY} >> /Unity_v2018.x.ulf
          /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile /Unity_v2018.x.ulf || exit 0
