name: Unity Test Runner Example

on:
  push:
    branches:
    - master

jobs:
  editorTestJob:
    strategy:
      matrix:
        unity-tag: [2018.4.9f1]
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    steps:
      - uses: actions/checkout@master
      - run: mkdir -p /artifact
      - run: openssl aes-256-cbc -d -in Unity_v2018.x.ulf-cipher -k ${CYPHER_KEY} >> /Unity_v2018.x.ulf
        env:
          CYPHER_KEY: ${{ secrets.cypherkey }}
      - name: Run Tests
        run: /opt/Unity/Editor/Unity -manualLicenseFile /Unity_v2018.x.ulf -batchmode -nographics -silent-crashes -logFile -projectPath . -runEditorTests -editorTestsResultFile ./results.xml || exit 0
      - run: ls /artifact
      - uses: actions/upload-artifact@master
        with:
          name: result
          path: /artifact
