name: Unity Test Runner Example

on:
  push:
    branches:
    - master

jobs:
  editorTestJob:
    strategy:
      matrix:
        unity-tag: [2018.4.9f1]
    runs-on: ubuntu-latest
    
    steps:
      - run: curl -X POST -H 'Content-type:application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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